- name: Install Git
  yum: 
    pkg: git
    state: latest
    update_cache: yes
- name: Install Docker
  yum:
    pkg: docker
    state: latest
    update_cache: yes
  notify:
    - Start Docker
- name: Allow docker cmds without sudo
  user:
    name: ec2-user
    group: docker
    append: yes
  notify:
    - Restart Docker
