- name: Start MySQL server 
  service: 
    name: mysql
    state: started
- name: Fetch init.sql
  shell: "curl https://raw.githubusercontent.com/slalomsv/simple-app/master/db/setup_db.sql > init.sql"
  args:
    creates: init.sql
- name: Run DB init script
  shell: "mysql -u admin -ppassword123 < init.sql"
